### 查询所有用户 / Get all users
GET http://localhost:8080/users

### 查询单个用户 / Get user by username
GET http://localhost:8080/users/tom

### 注册用户 / Register user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "spring01",
  "password": "123456"
}

### 用户登录 / Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "tom",
  "password": "123456"
}

### 修改密码 / Change password
PUT http://localhost:8080/users/spring01/password
Content-Type: application/json

{
  "password": "abcdef"
}

### 使用新密码登录 / Login with new password
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "spring01",
  "password": "abcdef"
}

### 删除用户 / Delete user
DELETE http://localhost:8080/users/spring01

### 测试参数校验 / Validation test
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "",
  "password": "123"
}

### 查看自己 / Get me
GET http://localhost:8080/me?username=tom

### 修改自己的密码 / Change my password
PUT http://localhost:8080/me/password?username=tom
Content-Type: application/json

{
  "username": "tom",
  "password": "abcdef"
}

### 管理员查询全部用户 / Admin get all users
GET http://localhost:8080/admin/users

### 管理员查询单个用户 / Admin get user
GET http://localhost:8080/admin/users/tom

### 管理员重置用户密码 / Admin reset password
PUT http://localhost:8080/admin/users/tom/password
Content-Type: application/json

{
  "username": "tom",
  "password": "123456"
}

### 管理员删除用户 / Admin delete user
DELETE http://localhost:8080/admin/users/spring01

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "tom",
  "password": "123456"
}

###
GET http://localhost:8080/me
Authorization: c

### 不带 token 访问 /me / Access /me without token
GET http://localhost:8080/me

### 登录获取 token / Login and get token
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "tom",
  "password": "123456"
}

### 带 token 访问 /me / Access /me with token
GET http://localhost:8080/me
Authorization: e68f5bbf-753f-48ed-8cc7-52b0fb901a84

###
GET http://localhost:8080/admin/users
Authorization: 3c2f999a-86a3-433e-83f9-1902a55f71d6